pub mod albedo_default;
pub mod arataki_itto_default;
pub mod gorou_default;
pub mod ningguang_default;
pub mod noelle_default;
pub mod yunjin_default;
pub mod zhongli_default;
pub mod navia_default;
pub mod chiori_default;

pub use albedo_default::AlbedoDefaultTargetFunction;
pub use arataki_itto_default::AratakiIttoDefaultTargetFunction;
pub use gorou_default::GorouDefaultTargetFunction;
pub use ningguang_default::NingguangDefaultTargetFunction;
pub use noelle_default::NoelleDefaultTargetFunction;
pub use yunjin_default::YunjinDefaultTargetFunction;
pub use zhongli_default::ZhongliDefaultTargetFunction;
pub use navia_default::NaviaDefaultTargetFunction;
pub use chiori_default::ChioriDefaultTargetFunction;
